## This function creates a special "matrix" object that can cache its inverse. It can be used as a generator function
## for a class of matrixes with cached inverses.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y){
    x <<- y
    inv <<- NULL
  }
  
  get <- function() x
  
  setinv <- function(y){
    inv <<- y
  }
  
  getinv <- function() inv

}


## This function computes the inverse of the special "matrix" class generated by makeCacheMatrix above. If the inverse 
## has already been calculated (and the matrix has not changed), then the cachesolve should retrieve the inverse
## from the cache

cacheSolve <- function(x, ...) {
  inv <- x$getinv()
  if (!is.null(inv) && matequal(x,x$get())){  ## we check if the inverse has been calculated already or the matrix has changed 
    message('Getting cached data')
    return(inv)
  }
  inv <- solve(x)
  x$setinv(inv)
  inv
}
## this function is used to check that two matrices are identical regardless of the name of their dimension (thats why we dont 
## use functions like identical() )
matequal <- function(x, y){
  is.matrix(x) && is.matrix(y) && dim(x) == dim(y) && all(x == y)
}
