## This is a function that given a single matrix class object  creates a special "matrix" object that can cache its inverse.
makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y){    
    ## In this point we assign the values y,NULL to the "global" variables x,inv. Those variable "exists" in the environment 
    ## outside the function set. For that we use the the super assign operator '<<-'. 
    x <<- y ## x is refered to here as a variable of the parent environment. On the other hand y exists only inside the function
            ## and is interchangable.
    inv <<- NULL ## We set inv to NULL in case of a change in x so we will have to recalculate inv in cacheSolve.
  }
  
  get <- function() x 
  
  setinv <- function(y) inv <<- y
  
  
  getinv <- function() inv
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)

}


## This function computes the inverse of the special "matrix" type generated by makeCacheMatrix above. If the inverse 
## has already been calculated (and the matrix has not changed), then the cachesolve will retrieve the inverse
## from the cache.

cacheSolve <- function(x, ...) {
  inv <- x$getinv()
  ## we check if the inverse has been calculated already 
  if (!is.null(inv)){  
    message('Getting cached data')
    return(inv)
  }
  data <- x$get()
  inv <- solve(data,...)
  x$setinv(inv)
  inv
}
